### PR TITLE
Build fix: glibc 2.35+

### PR DESCRIPTION
**Pull request by repojohnray**
In file included from sources/src/audio.c:46:
/usr/include/bits/mathcalls.h:133:1: error: expected ';' before 'extern'
 __MATHCALL_VEC (log2,, (_Mdouble_ __x));

The following defines: log2 and log2l were interacting with the
commit: 7e1722fec84c65bf95f249f9ad8d15ab12d8c853 from glibc

### CODE REVIEW

**Comment by sonninnos** [comment]
Those defines were added because some platforms (can't remember which) did not build without them. My current setup (Windows and Linux) builds fine though without them. And the pipeline is working, so why is this needed again?

And also I refuse changes to the codebase without `__LIBRETRO__` guards, so maybe there is a better way to handle this.

**Comment by asciibeats** [comment]
Got the same error and this fixed it for me. Compiling for aarch64. Thanks @repojohnray!

**Comment by LibretroAdmin** [comment]
Hi @repojohnray , I think @sonninnos is still waiting for a response. He had some questions as expressed above.

**Comment by repojohnray** [comment]
Hi @LibretroAdmin, I've no idea why these defines were implemented; I confirm these defines are not needed with Linux.

**Comment by octartis** [comment]
Fixed my build on Arch while building package `libretro-uae-git`

**Comment by veganvelociraptor** [comment]
This should be merged as soon as possible. I've been unable to build for months without this pr.

**Comment by sonninnos** [comment]
It won't be until the changes I requested are done, and until someone is willing to fix all the builds that will fail after merging.

**Comment by PanAeon** [comment]
This also blocks build on `NixOS`

**Comment by sonninnos** [comment]
I updated my Linux VM and finally got this failure too, and found another fix without editing `fpp_native.c`.

Please confirm.
